### ISSUE TITLE
install on OSX fail

### ISSUE THREAD

**Issue by joeblew99** [shurcooL/Conception-go#10]
go get -u github.com/shurcooL/Conception-go
package github.com/shurcooL/Conception-go
	imports github.com/bradfitz/iter
	imports github.com/go-gl/gl/v2.1/gl
	imports github.com/go-gl/glfw/v3.1/glfw
	imports github.com/go-gl/mathgl/mgl64
	imports golang.org/x/image/math/f64
	imports github.com/gogo/protobuf/proto
	imports github.com/golang/protobuf/proto
	imports github.com/gopherjs/gopherjs/build
	imports github.com/gopherjs/gopherjs/compiler
	imports github.com/gopherjs/gopherjs/compiler/analysis
	imports github.com/gopherjs/gopherjs/compiler/astutil
	imports golang.org/x/tools/go/exact
	imports golang.org/x/tools/go/types
	imports github.com/gopherjs/gopherjs/compiler/typesutil
	imports github.com/gopherjs/gopherjs/compiler/filter
	imports github.com/gopherjs/gopherjs/compiler/prelude
	imports golang.org/x/tools/go/importer
	imports golang.org/x/tools/go/types/typeutil
	imports github.com/gopherjs/gopherjs/gcexporter
	imports github.com/gopherjs/gopherjs/gcexporter
	imports github.com/gopherjs/gopherjs/gcexporter: cannot find package "github.com/gopherjs/gopherjs/gcexporter" in any of:
	/usr/local/go/src/github.com/gopherjs/gopherjs/gcexporter (from $GOROOT)
	/Users/apple/go/src/github.com/gopherjs/gopherjs/gcexporter (from $GOPATH)

**Comment by shurcooL** [comment]
This is a false positive. Everything updated correctly, it just prints an error message because an internal package moved. This is due to an issue in Go, reported at https://github.com/golang/go/issues/9224.

Try `go get -u github.com/shurcooL/Conception-go` a second time and there should be no error.

**Comment by joeblew99** [comment]
thanks for such quick reply Dmitri

yes i run it agin withe the -u again.
same errors.

But she builds and runs.
Quit fast runtime.

I am a fan of Victor also btw, so i had to take a look :)

**Comment by shurcooL** [comment]
Thanks for checking it out. :)
