### ISSUE TITLE
OSX startup has spinning beach ball :)

### ISSUE THREAD

**Issue by gedw99** [shurcooL/Conception-go#12]
i did a go get -u :)

go: 1.6

The GUI fires up, but is blank canvas, with the OSX BeachBall spinning (cant see it in the screenshot)

<img width="1280" alt="conception-go" src="https://cloud.githubusercontent.com/assets/20677314/17700668/13d4c116-63c7-11e6-940f-aa1c91d5f518.png">

````
x-MacBook-Pro:Conception-go apple$ Conception-go
go version go1.6.3 darwin/amd64.
glfw 3.2.1 Cocoa NSGL chdir menubar retina.
OpenGL Intel Inc. Intel Iris OpenGL Engine 2.1 INTEL-10.14.73; 1.20; 8 samples.
Loaded in 624.4662410000001 ms.
^C
x-MacBook-Pro:Conception-go apple$ 

`````

**Comment by shurcooL** [comment]
How many Go packages do you have in your workspace? Can you print output of:

```
go list all | wc -l

time go list all
```

It looks for all Go packages on startup and will take at least as long as `go list all`.

**Comment by gedw99** [comment]
Its ok. I found what was screwing it up.
glfw

I am running fuschia and vanadium.
the sky engine has glfw, and that messed it up.
